version: '3.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
    ports:
      - "8080:8080"

volumes:
  db-data: